In [1]:
import tensorflow as tf

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Single Layer Perceptron Dataset.csv')

In [5]:
df

    Pattern  Feature1  Feature2  Feature3  Class_Label
0       1.0       1.0      0.08      0.72          1.0
1       2.0       1.0      0.10      1.00          1.0
2       3.0       1.0      0.26      0.58          1.0
3       4.0       1.0      0.35      0.95          0.0
4       5.0       1.0      0.45      0.15          1.0
5       6.0       1.0      0.60      0.30          1.0
6       7.0       1.0      0.70      0.65          0.0
7       8.0       1.0      0.92      0.45          0.0
8       9.0       1.0      0.42      0.85          0.0
9      10.0       1.0      0.65      0.55          0.0
10     11.0       1.0      0.20      0.30          1.0
11     12.0       1.0      0.20      1.00          0.0
12     13.0       1.0      0.85      0.10          1.0
13      NaN       NaN       NaN       NaN          NaN

In [7]:
df=df.dropna()

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
df.loc[:, 'Pattern'] = sc.fit_transform(df[['Pattern']])

In [14]:
df

         Pattern  Feature1  Feature2  Feature3  Class_Label
0  -1.603567e+00       1.0      0.08      0.72          1.0
1  -1.336306e+00       1.0      0.10      1.00          1.0
2  -1.069045e+00       1.0      0.26      0.58          1.0
3  -8.017837e-01       1.0      0.35      0.95          0.0
4  -5.345225e-01       1.0      0.45      0.15          1.0
5  -2.672612e-01       1.0      0.60      0.30          1.0
6   5.124106e-17       1.0      0.70      0.65          0.0
7   2.672612e-01       1.0      0.92      0.45          0.0
8   5.345225e-01       1.0      0.42      0.85          0.0
9   8.017837e-01       1.0      0.65      0.55          0.0
10  1.069045e+00       1.0      0.20      0.30          1.0
11  1.336306e+00       1.0      0.20      1.00          0.0
12  1.603567e+00       1.0      0.85      0.10          1.0

In [18]:
from sklearn.model_selection import train_test_split
import numpy as np

X = df[['Pattern', 'Feature1', 'Feature2', 'Feature3']].values
y = df['Class_Label'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=5, batch_size=1, verbose=0, validation_split=0.2)

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)

In [19]:
print(f"Perceptron Model Accuracy: {accuracy*100:.2f}%")

Perceptron Model Accuracy: 66.67%